// src/lib/store.js
//
// A tiny localStorage-backed store for Decision Vitals. Everything lives under a
// single key so the whole app state can be inspected, exported, or cleared in one
// place. No database, no backend, per PLAN.md Section 4 and Section 13.
//
// Object shapes are documented as JSDoc typedefs below and match PLAN.md Section 4
// exactly. Helpers are grouped by entity: decisions, assumptions, evidence,
// agentRuns, reports. Deleting a decision cascades to everything that belongs to it.

const STORAGE_KEY = "decision_vitals_state";

/**
 * @typedef {"healthy" | "watch" | "at_risk" | null} HealthGrade
 *
 * @typedef {Object} Decision
 * @property {string} id
 * @property {string} title        Short label, generated by the Intake agent.
 * @property {string} statement    User input (or Intake-normalized statement).
 * @property {string} context
 * @property {string} owner
 * @property {string} createdAt    ISO string.
 * @property {HealthGrade} healthGrade
 *
 * @typedef {"load_bearing" | "vulnerable" | "lower_risk"} Tier
 * @typedef {"untested" | "holding" | "weakened" | "invalidated" | "needs_review"} AssumptionStatus
 *
 * @typedef {Object} Assumption
 * @property {string} id
 * @property {string} decisionId
 * @property {string} text
 * @property {boolean} loadBearing
 * @property {boolean} vulnerable
 * @property {Tier} tier           Derived label for the UI.
 * @property {string} signpost     Observable signal that this assumption is failing.
 * @property {AssumptionStatus} status
 * @property {boolean} userEdited
 *
 * @typedef {"meeting_notes" | "customer_feedback" | "support_ticket" | "market_update" | "status_update"} SourceType
 *
 * @typedef {Object} Evidence
 * @property {string} id
 * @property {string} decisionId
 * @property {string} text
 * @property {SourceType} sourceType
 * @property {string} date
 * @property {string} addedAt       ISO string.
 *
 * @typedef {"pending" | "running" | "done" | "error"} StepStatus
 *
 * @typedef {Object} AgentStep
 * @property {string} agent
 * @property {StepStatus} status
 * @property {string} inputSummary
 * @property {Object} output
 * @property {number} durationMs
 *
 * @typedef {Object} AgentRun
 * @property {string} id
 * @property {string} decisionId
 * @property {number} runNumber
 * @property {string} startedAt     ISO string.
 * @property {AgentStep[]} steps
 *
 * @typedef {Object} ReportReceipt
 * @property {string} evidenceId
 * @property {string} quote
 *
 * @typedef {Object} ReportFinding
 * @property {string} assumptionId
 * @property {string} status
 * @property {string} rationale
 * @property {ReportReceipt[]} receipts
 *
 * @typedef {Object} ReportAction
 * @property {"shaping" | "hedging"} type
 * @property {string} assumptionId
 * @property {string} text
 *
 * @typedef {Object} Report
 * @property {string} id
 * @property {string} decisionId
 * @property {string} runId
 * @property {number} runNumber
 * @property {string} createdAt     ISO string.
 * @property {"healthy" | "watch" | "at_risk"} healthGrade
 * @property {string} summary
 * @property {ReportFinding[]} findings
 * @property {string[]} challengeHighlights
 * @property {ReportAction[]} actions
 */

const EMPTY_STATE = {
  decisions: [],
  assumptions: [],
  evidence: [],
  agentRuns: [],
  reports: [],
};

// ---------------------------------------------------------------------------
// Low-level state read/write
// ---------------------------------------------------------------------------

function hasStorage() {
  return typeof window !== "undefined" && !!window.localStorage;
}

/** Read the entire state object, tolerating missing/corrupt storage. */
export function readState() {
  if (!hasStorage()) return { ...EMPTY_STATE };
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    if (!raw) return { ...EMPTY_STATE };
    const parsed = JSON.parse(raw);
    // Merge over EMPTY_STATE so a partial/old blob still has every collection.
    return { ...EMPTY_STATE, ...parsed };
  } catch {
    return { ...EMPTY_STATE };
  }
}

/** Persist the entire state object and notify subscribers. */
export function writeState(state) {
  if (hasStorage()) {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  }
  notify();
  return state;
}

/** Read, mutate via `fn`, write back. `fn` returns the next state. */
function updateState(fn) {
  const next = fn(readState());
  writeState(next);
  return next;
}

/** Wipe all Decision Vitals state. */
export function resetState() {
  return writeState({ ...EMPTY_STATE });
}

/** Replace all state at once (used by the sample-data loader). */
export function replaceState(state) {
  return writeState({ ...EMPTY_STATE, ...state });
}

// ---------------------------------------------------------------------------
// Reactivity: a minimal subscribe/notify so React screens can re-read on change
// ---------------------------------------------------------------------------

const listeners = new Set();

/** Subscribe to any store write. Returns an unsubscribe function. */
export function subscribe(listener) {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

function notify() {
  for (const listener of listeners) {
    try {
      listener();
    } catch {
      // A broken listener must not corrupt a write.
    }
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Collision-resistant id, with a fallback for older environments. */
function newId() {
  if (typeof crypto !== "undefined" && crypto.randomUUID) {
    return crypto.randomUUID();
  }
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}

function nowIso() {
  return new Date().toISOString();
}

// ---------------------------------------------------------------------------
// Decisions
// ---------------------------------------------------------------------------

/** @returns {Decision[]} */
export function listDecisions() {
  return readState().decisions;
}

/** @returns {Decision | undefined} */
export function getDecision(id) {
  return readState().decisions.find((d) => d.id === id);
}

/**
 * @param {Partial<Decision>} input
 * @returns {Decision}
 */
export function createDecision(input = {}) {
  /** @type {Decision} */
  const decision = {
    id: input.id ?? newId(),
    title: input.title ?? "",
    statement: input.statement ?? "",
    context: input.context ?? "",
    owner: input.owner ?? "",
    createdAt: input.createdAt ?? nowIso(),
    healthGrade: input.healthGrade ?? null,
  };
  updateState((s) => ({ ...s, decisions: [...s.decisions, decision] }));
  return decision;
}

/**
 * @param {string} id
 * @param {Partial<Decision>} patch
 * @returns {Decision | undefined}
 */
export function updateDecision(id, patch) {
  let updated;
  updateState((s) => ({
    ...s,
    decisions: s.decisions.map((d) =>
      d.id === id ? (updated = { ...d, ...patch, id: d.id }) : d
    ),
  }));
  return updated;
}

/** Delete a decision and cascade to its assumptions, evidence, runs, reports. */
export function deleteDecision(id) {
  updateState((s) => ({
    decisions: s.decisions.filter((d) => d.id !== id),
    assumptions: s.assumptions.filter((a) => a.decisionId !== id),
    evidence: s.evidence.filter((e) => e.decisionId !== id),
    agentRuns: s.agentRuns.filter((r) => r.decisionId !== id),
    reports: s.reports.filter((r) => r.decisionId !== id),
  }));
}

// ---------------------------------------------------------------------------
// Assumptions
// ---------------------------------------------------------------------------

/** @returns {Assumption[]} */
export function listAssumptions() {
  return readState().assumptions;
}

/** @returns {Assumption[]} All assumptions for one decision. */
export function assumptionsByDecision(decisionId) {
  return readState().assumptions.filter((a) => a.decisionId === decisionId);
}

/** @returns {Assumption | undefined} */
export function getAssumption(id) {
  return readState().assumptions.find((a) => a.id === id);
}

/**
 * @param {Partial<Assumption> & { decisionId: string }} input
 * @returns {Assumption}
 */
export function createAssumption(input) {
  /** @type {Assumption} */
  const assumption = {
    id: input.id ?? newId(),
    decisionId: input.decisionId,
    text: input.text ?? "",
    loadBearing: input.loadBearing ?? false,
    vulnerable: input.vulnerable ?? false,
    tier: input.tier ?? "lower_risk",
    signpost: input.signpost ?? "",
    status: input.status ?? "untested",
    userEdited: input.userEdited ?? false,
  };
  updateState((s) => ({ ...s, assumptions: [...s.assumptions, assumption] }));
  return assumption;
}

/** Create many assumptions in one write (e.g. from the Classifier output). */
export function createAssumptions(inputs = []) {
  const created = inputs.map((input) => ({
    id: input.id ?? newId(),
    decisionId: input.decisionId,
    text: input.text ?? "",
    loadBearing: input.loadBearing ?? false,
    vulnerable: input.vulnerable ?? false,
    tier: input.tier ?? "lower_risk",
    signpost: input.signpost ?? "",
    status: input.status ?? "untested",
    userEdited: input.userEdited ?? false,
  }));
  updateState((s) => ({ ...s, assumptions: [...s.assumptions, ...created] }));
  return created;
}

/**
 * @param {string} id
 * @param {Partial<Assumption>} patch
 * @returns {Assumption | undefined}
 */
export function updateAssumption(id, patch) {
  let updated;
  updateState((s) => ({
    ...s,
    assumptions: s.assumptions.map((a) =>
      a.id === id ? (updated = { ...a, ...patch, id: a.id }) : a
    ),
  }));
  return updated;
}

export function deleteAssumption(id) {
  updateState((s) => ({
    ...s,
    assumptions: s.assumptions.filter((a) => a.id !== id),
  }));
}

// ---------------------------------------------------------------------------
// Evidence
// ---------------------------------------------------------------------------

/** @returns {Evidence[]} */
export function listEvidence() {
  return readState().evidence;
}

/** @returns {Evidence[]} All evidence for one decision. */
export function evidenceByDecision(decisionId) {
  return readState().evidence.filter((e) => e.decisionId === decisionId);
}

/** @returns {Evidence | undefined} */
export function getEvidence(id) {
  return readState().evidence.find((e) => e.id === id);
}

/**
 * @param {Partial<Evidence> & { decisionId: string }} input
 * @returns {Evidence}
 */
export function createEvidence(input) {
  /** @type {Evidence} */
  const evidence = {
    id: input.id ?? newId(),
    decisionId: input.decisionId,
    text: input.text ?? "",
    sourceType: input.sourceType ?? "meeting_notes",
    date: input.date ?? "",
    addedAt: input.addedAt ?? nowIso(),
  };
  updateState((s) => ({ ...s, evidence: [...s.evidence, evidence] }));
  return evidence;
}

/**
 * Evidence is immutable once a review has used it (PLAN.md Section 13). This
 * helper exists for pre-review corrections only; screens gate it accordingly.
 * @param {string} id
 * @param {Partial<Evidence>} patch
 */
export function updateEvidence(id, patch) {
  let updated;
  updateState((s) => ({
    ...s,
    evidence: s.evidence.map((e) =>
      e.id === id ? (updated = { ...e, ...patch, id: e.id }) : e
    ),
  }));
  return updated;
}

export function deleteEvidence(id) {
  updateState((s) => ({
    ...s,
    evidence: s.evidence.filter((e) => e.id !== id),
  }));
}

// ---------------------------------------------------------------------------
// Agent runs
// ---------------------------------------------------------------------------

/** @returns {AgentRun[]} */
export function listAgentRuns() {
  return readState().agentRuns;
}

/** @returns {AgentRun[]} Runs for a decision, oldest first. */
export function runsByDecision(decisionId) {
  return readState()
    .agentRuns.filter((r) => r.decisionId === decisionId)
    .sort((a, b) => a.runNumber - b.runNumber);
}

/** @returns {AgentRun | undefined} */
export function getAgentRun(id) {
  return readState().agentRuns.find((r) => r.id === id);
}

/** Next 1-based review number for a decision. */
export function nextRunNumber(decisionId) {
  const runs = readState().agentRuns.filter((r) => r.decisionId === decisionId);
  return runs.reduce((max, r) => Math.max(max, r.runNumber), 0) + 1;
}

/**
 * @param {Partial<AgentRun> & { decisionId: string }} input
 * @returns {AgentRun}
 */
export function createAgentRun(input) {
  /** @type {AgentRun} */
  const run = {
    id: input.id ?? newId(),
    decisionId: input.decisionId,
    runNumber: input.runNumber ?? nextRunNumber(input.decisionId),
    startedAt: input.startedAt ?? nowIso(),
    steps: input.steps ?? [],
  };
  updateState((s) => ({ ...s, agentRuns: [...s.agentRuns, run] }));
  return run;
}

/**
 * @param {string} id
 * @param {Partial<AgentRun>} patch
 * @returns {AgentRun | undefined}
 */
export function updateAgentRun(id, patch) {
  let updated;
  updateState((s) => ({
    ...s,
    agentRuns: s.agentRuns.map((r) =>
      r.id === id ? (updated = { ...r, ...patch, id: r.id }) : r
    ),
  }));
  return updated;
}

export function deleteAgentRun(id) {
  updateState((s) => ({
    ...s,
    agentRuns: s.agentRuns.filter((r) => r.id !== id),
  }));
}

/**
 * Delete this decision's runs that never produced a report (failed or
 * abandoned mid-pipeline). Called before starting a fresh run so review
 * numbering stays contiguous with actual reports.
 */
export function purgeOrphanRuns(decisionId) {
  updateState((s) => {
    const reported = new Set(s.reports.map((r) => r.runId));
    return {
      ...s,
      agentRuns: s.agentRuns.filter(
        (r) => r.decisionId !== decisionId || reported.has(r.id)
      ),
    };
  });
}

// ---------------------------------------------------------------------------
// Reports
// ---------------------------------------------------------------------------

/** @returns {Report[]} */
export function listReports() {
  return readState().reports;
}

/** @returns {Report[]} Reports for a decision, oldest first. */
export function reportsByDecision(decisionId) {
  return readState()
    .reports.filter((r) => r.decisionId === decisionId)
    .sort((a, b) => a.runNumber - b.runNumber);
}

/** @returns {Report | undefined} */
export function getReport(id) {
  return readState().reports.find((r) => r.id === id);
}

/** @returns {Report | undefined} The report produced by a given run. */
export function reportByRun(runId) {
  return readState().reports.find((r) => r.runId === runId);
}

/**
 * @param {Partial<Report> & { decisionId: string, runId: string }} input
 * @returns {Report}
 */
export function createReport(input) {
  /** @type {Report} */
  const report = {
    id: input.id ?? newId(),
    decisionId: input.decisionId,
    runId: input.runId,
    runNumber: input.runNumber ?? nextRunNumber(input.decisionId),
    createdAt: input.createdAt ?? nowIso(),
    healthGrade: input.healthGrade ?? "healthy",
    summary: input.summary ?? "",
    findings: input.findings ?? [],
    challengeHighlights: input.challengeHighlights ?? [],
    actions: input.actions ?? [],
  };
  updateState((s) => ({ ...s, reports: [...s.reports, report] }));
  return report;
}

/**
 * @param {string} id
 * @param {Partial<Report>} patch
 * @returns {Report | undefined}
 */
export function updateReport(id, patch) {
  let updated;
  updateState((s) => ({
    ...s,
    reports: s.reports.map((r) =>
      r.id === id ? (updated = { ...r, ...patch, id: r.id }) : r
    ),
  }));
  return updated;
}

export function deleteReport(id) {
  updateState((s) => ({
    ...s,
    reports: s.reports.filter((r) => r.id !== id),
  }));
}
